version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: "${app_name}_db"
    ports:
      - "${db_port}:${db_port}"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 5
      
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "${app_name}_backend"
    ports:
      - "${server_port}:${server_port}"
    depends_on:
      mongo:
        condition: service_healthy      
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://mongo:${db_port}/${app_name}"
      SPRING_APPLICATION_NAME: "${app_name}"

volumes:
  mongo_data: