apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}-backend
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.serverPort }}
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://{{ .Values.appName }}-mongo:{{ .Values.dbPort }}/{{ .Values.appName }}
            - name: SPRING_APPLICATION_NAME
              value: {{ .Values.appName }}