apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}-mongo
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-mongo
    spec:
      containers:
        - name: mongo
          image: {{ .Values.mongo.image }}
          ports:
            - containerPort: {{ .Values.dbPort }}
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc