apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-backend
spec:
  selector:
    app: {{ .Values.appName }}-backend
  ports:
    - port: {{ .Values.serverPort }}
      targetPort: {{ .Values.serverPort }}
      nodePort: 30000
  type: NodePort